\begin{minipage}[b]{0.45\linewidth}
\centering

<<fig.align="center">>=
ggplot(dat,aes(factor(Class),fill=factor(Class))) + 
geom_bar() + 
xlab('Class') + 
labs(fill = "Class", title="All chimeras")
@

\end{minipage}
\hspace{0.5cm}
\begin{minipage}[b]{0.45\linewidth}
\centering

<<fig.align="center">>=
ggplot(subset(dat,Rank==100),aes(factor(Class),fill=factor(Class))) + 
geom_bar() + 
xlab('Class') + 
labs(fill = "Class", title="Best chimeras (within a rank of 100)")
@

\end{minipage}
